{
 "title": "AWS Backup Health",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "DynamoDB Backup Compliance",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "--SELECT COUNT(resource_arn), resource_type \n--FROM aws_backup_protected_resources \n--GROUP BY resource_type LIMIT 50;\n\nDROP TABLE if EXISTS resource_count; \n\nCREATE TABLE resource_count (\n\tcounted int,\n\tresource_name varchar(255)\n);\n\nINSERT INTO resource_count(counted, resource_name)\nSELECT COUNT(arn), 'S3' FROM aws_s3_buckets;\n\nINSERT INTO resource_count(counted, resource_name)\nSELECT COUNT(arn), 'EC2' FROM aws_ec2_instances;\n\nINSERT INTO resource_count(counted, resource_name)\nSELECT COUNT(arn), 'DynamoDB' FROM aws_dynamodb_tables;\n\n    SELECT resource_type, backupcount as complaintresources, counted-backupcount as unprotectedresources from\n    ( SELECT COUNT(resource_arn) as backupcount, resource_type\n    FROM aws_backup_protected_resources \n    GROUP BY resource_type \n    ) as backup_numbers\n  LEFT JOIN resource_count\n  ON backup_numbers.resource_type = resource_count.resource_name\n  WHERE resource_type = 'DynamoDB'\n  ;\n"
    }
   ]
  },
  {
   "title": "EC2 Backup Compliance",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "--SELECT COUNT(resource_arn), resource_type \n--FROM aws_backup_protected_resources \n--GROUP BY resource_type LIMIT 50;\n\nDROP TABLE if EXISTS resource_count; \n\nCREATE TABLE resource_count (\n\tcounted int,\n\tresource_name varchar(255)\n);\n\nINSERT INTO resource_count(counted, resource_name)\nSELECT COUNT(arn), 'S3' FROM aws_s3_buckets;\n\nINSERT INTO resource_count(counted, resource_name)\nSELECT COUNT(arn), 'EC2' FROM aws_ec2_instances;\n\nINSERT INTO resource_count(counted, resource_name)\nSELECT COUNT(arn), 'DynamoDB' FROM aws_dynamodb_tables;\n\n    SELECT resource_type, backupcount as complaintresources, counted-backupcount as unprotectedresources from\n    ( SELECT COUNT(resource_arn) as backupcount, resource_type\n    FROM aws_backup_protected_resources \n    GROUP BY resource_type \n    ) as backup_numbers\n  LEFT JOIN resource_count\n  ON backup_numbers.resource_type = resource_count.resource_name\n  WHERE resource_type = 'EC2'\n  ;\n"
    }
   ]
  },
  {
   "title": "S3 Backup Compliance",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "--SELECT COUNT(resource_arn), resource_type \n--FROM aws_backup_protected_resources \n--GROUP BY resource_type LIMIT 50;\n\nDROP TABLE if EXISTS resource_count; \n\nCREATE TABLE resource_count (\n\tcounted int,\n\tresource_name varchar(255)\n);\n\nINSERT INTO resource_count(counted, resource_name)\nSELECT COUNT(arn), 'S3' FROM aws_s3_buckets;\n\nINSERT INTO resource_count(counted, resource_name)\nSELECT COUNT(arn), 'EC2' FROM aws_ec2_instances;\n\nINSERT INTO resource_count(counted, resource_name)\nSELECT COUNT(arn), 'DynamoDB' FROM aws_dynamodb_tables;\n\n    SELECT resource_type, backupcount as complaintresources, counted-backupcount as unprotectedresources from\n    ( SELECT COUNT(resource_arn) as backupcount, resource_type\n    FROM aws_backup_protected_resources \n    GROUP BY resource_type \n    ) as backup_numbers\n  LEFT JOIN resource_count\n  ON backup_numbers.resource_type = resource_count.resource_name\n  WHERE resource_type = 'S3'\n  ;\n"
    }
   ]
  },
  {
   "title": "Protected Resources by AWS Backup",
   "type": "table",
   "description": "Resources backed up by AWS Backup",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT last_backup_time, resource_name, resource_type, resource_arn, account_id FROM aws_backup_protected_resources LIMIT 50 "
    }
   ]
  },
  {
   "title": "Protected Resources by Type",
   "type": "barchart",
   "description": "Resources Backed up",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(arn), resource_type FROM aws_backup_protected_resources GROUP BY resource_type LIMIT 50 "
    }
   ]
  },
  {
   "title": "Backup Job Health",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n\tCOUNT(backup_job_id), state,\n\tCASE WHEN status_message is NULL THEN 'true'\n\tELSE 'With Error'\n\tEND as status\n\t\nFROM aws_backup_jobs\nGROUP BY state, status"
    }
   ]
  },
  {
   "title": "Backup Jobs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT backup_job_id, state, status_message, resource_arn FROM aws_backup_jobs LIMIT 50 "
    }
   ]
  }
 ]
}