{
 "title": "AWS Compliance CSPM Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "account_id",
    "query": "select distinct account_id from \"${frameworks}\""
   },
   {
    "name": "status",
    "query": "select distinct status from \"${frameworks}\""
   },
   { "name": "DS_POSTGRESQL", "label": "Postgres Datasource", "query": "postgres" },
   {
    "name": "frameworks",
    "label": "Compliance Frameworks",
    "query": " select table_name from INFORMATION_SCHEMA.views WHERE table_schema = ANY (current_schemas(false)) AND \ntable_name != 'aws_resources' and table_name != 'aws_tables'\nAND table_name != 'aws_compliance__log_metric_filter_and_alarm'\nAND table_name NOT LIKE 'aws_compliance__security_group%'\nAND table_name NOT LIKE 'aws_compliance__network%'\nAND table_name NOT LIKE 'aws_compliance__api%'\nAND table_name NOT LIKE 'aws_encryption%'\nAND table_name != 'aws_data_resilience'"
   }
  ]
 },
 "panels": [
  { "title": "CloudQuery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data Source",
   "type": "stat",
   "description": "This panel will show OK if the aws_resources view has been created and is accessible to the current Postgres user. See https://github.com/cloudquery/cloudquery/tree/main/plugins/source/aws/dashboards for more information.",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM information_schema.views\n     WHERE table_name   = '${frameworks}'"
    }
   ]
  },
  {
   "title": "Last Fetch",
   "type": "stat",
   "description": "Time since the most recent CloudQuery fetch happened.",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select _cq_sync_time as time, 1 from aws_resources order by _cq_sync_time desc limit 1;"
    }
   ]
  },
  {
   "title": "Last Policy Execution",
   "type": "stat",
   "description": "Time since the most recent policy execution happened.",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select policy_execution_time as time, 1 from \"${frameworks}\" order by policy_execution_time desc limit 1;"
    }
   ]
  },
  { "title": "Results", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Policy Pass/Fail Distribution",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\nSELECT \n-- execution_time as time,\ncount(case when status = 'fail' then 1 else null end) as fail,\ncount(case when status = 'pass' then 1 else null end) as pass\n\nFROM \"${frameworks}\" where account_id in (${account_id}) \n\n--select\n  -- execution_time as time,\n--  framework,\n--  count(case when status = 'fail' then 1 else null end) as fail,\n  -- count(*)\n--  count(case when status = 'pass' then 1 else null end) as pass\n--from aws_policy_results where account_id in (${account_id}) and framework in (${framework}) group by framework;"
    }
   ]
  },
  {
   "title": "Failed Checks",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\nSELECT \n-- execution_time as time,\ncount(case when status = 'fail' then 1 else null end) as fail\n\nFROM \"${frameworks}\" where account_id in (${account_id}) "
    }
   ]
  },
  {
   "title": "Passed Checks",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\nSELECT \n-- execution_time as time,\ncount(case when status = 'pass' then 1 else null end) as pass\n \nFROM \"${frameworks}\" where account_id in (${account_id}) "
    }
   ]
  },
  {
   "title": "Policy Results",
   "type": "table",
   "description": "All policies, benchmarks results.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "select * from \"${frameworks}\" \nwhere account_id in (${account_id}) and status in (${status}) ;\n"
    }
   ]
  }
 ]
}