name: aws_encryption
version: 2.0.6
config-version: 2
profile: aws_encryption
model-paths:
  - models
  - ../models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - ../macros
  - ../../macros
snapshot-paths:
  - snapshots
clean-targets:
  - target
  - dbt_packages
models:
  aws_encryption:
    aws_encryption__encrypted_resources:
      +enabled: true
    aws_encryption__resources_encrypted_by_key:
      +enabled: true
    aws_encryption__encryption_keys:
      +enabled: true
    aws_encryption__keys_by_account:
      +enabled: true
