{
 "title": "AWS Cost",
 "time": { "from": "2023-07-24T00:00:00.000Z", "to": "2023-07-26T15:00:00.000Z" },
 "templating": {
  "list": [
   { "name": "cost_table", "query": "${VAR_COST_TABLE}" }
  ]
 },
 "panels": [
  {
   "title": "Cost By Region",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  product_location,\n  sum(line_item_blended_cost) AS cost\nFROM ${cost_table}\nWHERE line_item_resource_id !='' and product_location_type = 'AWS Region' and product_location != 'Any'\nGROUP BY product_location\nHAVING sum(line_item_blended_cost) > 0\nORDER BY cost DESC;"
    }
   ]
  },
  {
   "title": "Cost By Service",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  line_item_product_code,\n  sum(line_item_blended_cost) AS cost\nFROM ${cost_table}\nWHERE line_item_resource_id !=''\nGROUP BY line_item_product_code\nHAVING sum(line_item_blended_cost) > 0\nORDER BY cost DESC;"
    }
   ]
  },
  {
   "title": "Cost over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  line_item_usage_start_date,\n  line_item_usage_end_date,\n  sum(line_item_blended_cost) AS cost\nFROM ${cost_table}\nWHERE line_item_resource_id !='' and product_location_type = 'AWS Region'\nGROUP BY line_item_usage_start_date, line_item_usage_end_date\nORDER BY line_item_usage_start_date asc;"
    }
   ]
  }
 ]
}