name: k8s_compliance
version: 0.4.0
config-version: 2
profile: k8s_compliance
model-paths:
  - models
  - ../models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
  - ../macros
  - ../../macros
snapshot-paths:
  - snapshots
clean-targets:
  - target
  - dbt_packages
models:
  k8s_compliance: null
