name: k8s_compliance
version: 0.6.2
config-version: 2
profile: k8s_compliance
model-paths:
  - models
  - ../models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
  - ../macros
  - ../../macros
snapshot-paths:
  - snapshots
clean-targets:
  - target
  - dbt_packages
vars:
  cis_v1_8:
    - k8s_networking_network_policies
    - k8s_rbac_cluster_role_bindings
    - k8s_core_pods
    - k8s_rbac_cluster_roles
    - k8s_core_namespaces
    - k8s_core_service_accounts
    - k8s_rbac_roles
  nsa_cisa_v1:
    - k8s_networking_network_policies
    - k8s_core_pods
    - k8s_core_namespaces
    - k8s_core_service_accounts
    - k8s_apps_daemon_sets
    - k8s_apps_replica_sets
    - k8s_apps_deployments
    - k8s_core_resource_quotas
    - k8s_core_limit_ranges
    - k8s_batch_jobs
  k8s_models:
    - k8s_networking_network_policies
    - k8s_rbac_roles
    - k8s_rbac_cluster_roles
    - k8s_core_resource_quotas
    - k8s_core_limit_ranges
    - k8s_core_namespaces
    - k8s_core_service_accounts
    - k8s_rbac_cluster_role_bindings
    - k8s_apps_daemon_sets
    - k8s_batch_jobs
    - k8s_apps_replica_sets
    - k8s_core_pods
    - k8s_apps_deployments
