{
 "title": "dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "label": "data source", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Usage Cost",
     "type": "stat",
     "description": "The total cost incurred from resource usage, excluding credits or discounts.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select ROUND(total::numeric, 2) || '$' as cost from aws_cost__total\nwhere type = 'Usage'"
      }
     ]
    },
    {
     "title": "Total Credit Cost",
     "type": "stat",
     "description": "The total cost offset by credits or discounts, reducing the overall cost.",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select ROUND(total::numeric, 2) || '$' as cost from aws_cost__total\nwhere type = 'Credit'"
      }
     ]
    },
    {
     "title": "Overall Cost",
     "type": "stat",
     "description": "The total cost including both usage and credit costs, reflecting the actual amount paid.",
     "gridPos": { "h": 4, "w": 5, "x": 6, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select ROUND(total::numeric, 2) || '$' as cost from aws_cost__total\nwhere type = 'Overall'"
      }
     ]
    },
    {
     "title": "Total number of Resources",
     "type": "stat",
     "description": "The total count of resources considered in the cost analysis.",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select count(*) from aws_cost__by_resources"
      }
     ]
    },
    {
     "title": "Overall Cost Trend over Time",
     "type": "timeseries",
     "description": "A time series chart showing the trend of overall costs over a period of time, indicating how costs have changed over time.",
     "gridPos": { "h": 19, "w": 10, "x": 14, "y": 1 },
     "targets": [
      {
       "rawSql": "select * from aws_cost__over_time_date"
      }
     ]
    },
    {
     "title": "Cost Distribution per Service in AWS",
     "type": "piechart",
     "description": "A visual breakdown of costs by AWS service, showing the proportion of costs attributed to each service.",
     "gridPos": { "h": 15, "w": 6, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select * from aws_cost__by_product"
      }
     ]
    },
    {
     "title": "Cost Breakdown per Service in AWS",
     "type": "barchart",
     "description": "A graphical representation of costs per AWS service, displaying the cost amount for each service in a bar format.",
     "gridPos": { "h": 15, "w": 8, "x": 6, "y": 5 },
     "targets": [
      {
       "rawSql": "select * from aws_cost__by_product"
      }
     ]
    },
    {
     "title": "Cost Distribution per Account in AWS",
     "type": "piechart",
     "description": "A donut chart illustrating the distribution of costs among different AWS accounts.",
     "gridPos": { "h": 19, "w": 6, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select * from aws_cost__by_account"
      }
     ]
    },
    {
     "title": "Cost Distribution per Region in AWS",
     "type": "piechart",
     "description": "A pie chart displaying the distribution of costs across AWS regions, showcasing the proportion of costs in each region.",
     "gridPos": { "h": 19, "w": 8, "x": 6, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select * from aws_cost__by_regions"
      }
     ]
    },
    {
     "title": "Top 10 Most Costly Resources in AWS",
     "type": "barchart",
     "description": "A bar plot highlighting the top 10 resources that incur the highest costs in AWS, showing the cost amount for each resource.",
     "gridPos": { "h": 19, "w": 10, "x": 14, "y": 20 },
     "targets": [
      {
       "rawSql": "select * from aws_cost__by_resources\norder by cost desc\nLIMIT 10"
      }
     ]
    },
    {
     "title": "Top 10 Most Costly Resources in AWS",
     "type": "table",
     "description": "A table listing the top 10 resources with the highest costs in AWS.",
     "gridPos": { "h": 15, "w": 10, "x": 14, "y": 39 },
     "targets": [
      {
       "rawSql": "select line_item_resource_id as resource_id, line_item_product_code as service, cost  from aws_cost__by_resources\norder by cost desc\nLIMIT 10"
      }
     ]
    }
   ]
  },
  { "title": "EC2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "EC2 Instance count",
   "type": "stat",
   "description": "Displays the total count of EC2 instances.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select * from aws_cost__ec2_instance_count"
    }
   ]
  },
  {
   "title": "Total EC2 Cost",
   "type": "stat",
   "description": "Shows the total cost associated with EC2 instances.",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select ROUND(total_cost::numeric, 2) || '$' as cost from aws_cost__ec2_overall_cost\n"
    }
   ]
  },
  {
   "title": "Cost by Instance Type",
   "type": "barchart",
   "description": "Breaks down the cost based on the type of EC2 instances.",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 2 },
   "targets": [
    {
     "rawSql": "select * from aws_cost__ec2_cost_by_instance_type"
    }
   ]
  },
  {
   "title": "Cost Trend over Time",
   "type": "timeseries",
   "description": "Shows the trend of EC2 costs over a specific period.",
   "gridPos": { "h": 17, "w": 8, "x": 16, "y": 2 },
   "targets": [
    {
     "rawSql": "select * from aws_cost__ec2_cost_over_time"
    }
   ]
  },
  {
   "title": "EC2 Instane Status",
   "type": "table",
   "description": "Provides the status of EC2 instances.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "select * from aws_cost__ec2_instance_status"
    }
   ]
  },
  {
   "title": "Top 10 Most Costly EC2 Instances in AWS",
   "type": "barchart",
   "description": "Lists the top 10 EC2 instances with the highest costs.",
   "gridPos": { "h": 19, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "select * from aws_cost__ec2_cost_breakdown\norder by cost desc\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Cost by Region",
   "type": "piechart",
   "description": "Displays the cost distribution across different AWS regions.",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select * from aws_cost__ec2_cost_by_region"
    }
   ]
  },
  {
   "title": "Top Utilized Instances",
   "type": "barchart",
   "description": "Displays the most utilized EC2 instances based on metrics like CPU utilization. It includes the instance ARN, instance type, mean utilization, and associated cost.",
   "gridPos": { "h": 19, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "rawSql": "select * from aws_cost__ec2_instance_utilization_cost"
    }
   ]
  },
  {
   "title": "Top 10 Most Costly EC2 Instances in AWS",
   "type": "table",
   "description": "Lists the top 10 EC2 instances with the highest costs.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "select * from aws_cost__ec2_cost_breakdown\norder by cost desc\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Cost Savings Opportunities - optimization recommendations",
   "type": "table",
   "description": "Highlights potential cost-saving opportunities for EC2 instances based on optimization recommendations.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "targets": [
    {
     "rawSql": "select * from ec2_instances_optimization_recommendations"
    }
   ]
  },
  {
   "title": "Top Utilized Instances",
   "type": "table",
   "description": "Displays the most utilized EC2 instances based on metrics like CPU utilization. It includes the instance ARN, instance type, mean utilization, and associated cost.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 38 },
   "targets": [
    {
     "rawSql": "select * from aws_cost__ec2_instance_utilization_cost"
    }
   ]
  },
  {
   "title": "Cost Savings Opportunities - trusted advisor",
   "type": "table",
   "description": "Displays cost-saving opportunities identified by AWS Trusted Advisor.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
   "targets": [
    {
     "rawSql": "select account_id, arn, category, id, name, description, status from aws_cost__trusted_advisior_by_arn\nwhere arn like '%ec2%'"
    }
   ]
  }
 ]
}