{
 "title": "AWS Policies",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "account_id",
    "label": "account_id",
    "query": {}
   },
   {
    "name": "framework",
    "label": "framework",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pass / Fail overtime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "-- SELECT \n-- \t $__timeGroup(execution_time, $__interval) as time,\n--  FROM <metric_table>\n--  WHERE $__timeFilter(time)\n-- select framework, account_id from aws_policy_results where\n-- execution_time = (\n--   SELECT MAX(execution_time)\n--   FROM aws_policy_results\n-- );\n\nselect \n     $__timeGroup(execution_time, $__interval) as time,\n    pass\nfrom (\nSELECT \n  execution_time,\n  framework, \n  COUNT(CASE WHEN status = 'pass' THEN 1 END) AS pass, \n  COUNT(CASE WHEN STATUS = 'fail' THEN 1 END) AS fail\nFROM \n  aws_policy_results\nGROUP BY \n  framework, execution_time order by execution_time);"
    },
    {
     "rawSql": "select \n     $__timeGroup(execution_time, $__interval) as time,\n    fail\nfrom (\nSELECT \n  execution_time,\n  framework, \n  COUNT(CASE WHEN status = 'pass' THEN 1 END) AS pass, \n  COUNT(CASE WHEN STATUS = 'fail' THEN 1 END) AS fail\nFROM \n  aws_policy_results\nGROUP BY \n  framework, execution_time order by execution_time);"
    }
   ]
  },
  {
   "title": "Pass / Fail by Framework",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "-- select * from aws_policy_results where\n-- execution_time = (\n--   SELECT MAX(execution_time)\n--   FROM aws_policy_results\n-- );\n\nselect \n    framework,\n    account_id,\n    pass,\n    fail\nfrom (\nSELECT \n  framework,\n  account_id,\n  COUNT(CASE WHEN status = 'pass' THEN 1 END) AS pass, \n  COUNT(CASE WHEN STATUS = 'fail' THEN 1 END) AS fail\nFROM \n  aws_policy_results\nwhere execution_time = (\n  SELECT MAX(execution_time)\n  FROM aws_policy_results\n) and REGEXP_LIKE(account_id, '${account_id:regex}') and REGEXP_LIKE(framework, '${framework:regex}')\nGROUP BY  framework, account_id );\n"
    }
   ]
  },
  {
   "title": "Last AWS Policy Results",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "select * from aws_policy_results where\nexecution_time = (\n  SELECT MAX(execution_time)\n  FROM aws_policy_results\n) and REGEXP_LIKE(account_id, '${account_id:regex}') and REGEXP_LIKE(framework, '${framework:regex}')"
    }
   ]
  }
 ]
}