{
 "title": "AWS Backup Health",
 "templating": {
  "list": [
   { "name": "DS_POSTGRESQL", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "DynamoDB Backup Compliance",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n       sum(case when last_backup_time  is null then 1 else 0 end) as unprotectedresources,\n       sum(case when last_backup_time is not null then 1 else 0 end) as compliantresources\n  from aws_data_resilience__overview\n  WHERE resource_type='DynamoDB'"
    }
   ]
  },
  {
   "title": "EC2 Backup Compliance",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n       sum(case when last_backup_time  is null then 1 else 0 end) as unprotectedresources,\n       sum(case when last_backup_time is not null then 1 else 0 end) as compliantresources\n  from aws_data_resilience__overview\n  WHERE resource_type='EC2'"
    }
   ]
  },
  {
   "title": "S3 Backup Compliance",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n       sum(case when last_backup_time  is null then 1 else 0 end) as unprotectedresources,\n       sum(case when last_backup_time is not null then 1 else 0 end) as compliantresources\n  from aws_data_resilience__overview\n  WHERE resource_type='S3'"
    }
   ]
  },
  {
   "title": "Protected Resources by AWS Backup",
   "type": "table",
   "description": "Resources backed up by AWS Backup",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT last_backup_time, resource_name, resource_type, resource_arn, account_id FROM aws_backup_protected_resources "
    }
   ]
  },
  {
   "title": "Protected Resources by Type",
   "type": "barchart",
   "description": "Resources Backed up",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(arn), resource_type FROM aws_backup_protected_resources GROUP BY resource_type"
    },
    {}
   ]
  },
  {
   "title": "Backup Job Health",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n\tCOUNT(backup_job_id), state,\n\tCASE WHEN status_message is NULL THEN 'true'\n\tELSE 'With Error'\n\tEND as status\n\t\nFROM aws_backup_jobs\nGROUP BY state, status"
    }
   ]
  },
  {
   "title": "Backup Jobs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT backup_job_id, state, status_message, resource_arn FROM aws_backup_jobs"
    }
   ]
  }
 ]
}