name: azure_compliance
version: 0.8.6
config-version: 2
profile: azure_compliance
model-paths:
  - models
  - ../models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - ../macros
  - ../../macros
snapshot-paths:
  - snapshots
clean-targets:
  - target
  - dbt_packages
vars:
  cis_v1_3_0:
    - azure_monitor_activity_log_alerts
    - azure_keyvault_keyvault
    - azure_appservice_web_app_auth_settings
    - azure_storage_accounts
    - azure_sql_server_admins
    - azure_monitor_resources
    - azure_appservice_web_apps
    - azure_containerservice_managed_clusters
    - azure_sql_servers
    - azure_postgresql_server_firewall_rules
    - azure_appservice_web_app_configurations
    - azure_sql_server_firewall_rules
    - azure_authorization_role_definitions
    - azure_sql_server_advanced_threat_protection_settings
    - azure_sql_server_database_blob_auditing_policies
    - azure_compute_virtual_machines
    - azure_monitor_subscription_diagnostic_settings
    - azure_security_pricings
    - azure_compute_disks
    - azure_postgresql_server_configurations
    - azure_sql_transparent_data_encryptions
    - azure_storage_containers
    - azure_security_auto_provisioning_settings
    - azure_sql_server_databases
    - azure_keyvault_keyvault_secrets
    - azure_monitor_diagnostic_settings
    - azure_sql_server_vulnerability_assessments
    - azure_storage_blob_services
    - azure_network_watcher_flow_logs
    - azure_mysql_servers
    - azure_postgresql_servers
    - azure_keyvault_keyvault_keys
    - azure_sql_server_blob_auditing_policies
    - azure_sql_server_encryption_protectors
    - azure_network_security_groups
    - azure_policy_assignments
  cis_v2_0_0:
    - azure_monitor_activity_log_alerts
    - azure_keyvault_keyvault
    - azure_appservice_web_app_auth_settings
    - azure_storage_accounts
    - azure_sql_server_admins
    - azure_monitor_resources
    - azure_appservice_web_apps
    - azure_containerservice_managed_clusters
    - azure_sql_servers
    - azure_postgresql_server_firewall_rules
    - azure_network_watchers
    - azure_network_bastion_hosts
    - azure_appservice_web_app_configurations
    - azure_sql_server_firewall_rules
    - azure_authorization_role_definitions
    - azure_sql_server_advanced_threat_protection_settings
    - azure_sql_server_database_blob_auditing_policies
    - azure_security_contacts
    - azure_subscription_subscriptions
    - azure_compute_virtual_machines
    - azure_monitor_subscription_diagnostic_settings
    - azure_security_pricings
    - azure_compute_disks
    - azure_postgresql_server_configurations
    - azure_sql_transparent_data_encryptions
    - azure_network_virtual_networks
    - azure_storage_containers
    - azure_applicationinsights_components
    - azure_security_auto_provisioning_settings
    - azure_sql_server_databases
    - azure_keyvault_keyvault_secrets
    - azure_monitor_diagnostic_settings
    - azure_sql_server_vulnerability_assessments
    - azure_storage_blob_services
    - azure_mysql_servers
    - azure_network_watcher_flow_logs
    - azure_mysql_server_configurations
    - azure_postgresql_servers
    - azure_keyvault_keyvault_keys
    - azure_mysqlflexibleservers_servers
    - azure_sql_server_encryption_protectors
    - azure_sql_server_blob_auditing_policies
    - azure_mysqlflexibleservers_server_configurations
    - azure_policy_assignments
    - azure_network_security_groups
  cis_v2_1_0:
    - azure_postgresql_server_configurations
    - azure_security_auto_provisioning_settings
    - azure_compute_virtual_machines
    - azure_mysqlflexibleservers_server_configurations
    - azure_authorization_role_definitions
    - azure_security_pricings
    - azure_sql_server_encryption_protectors
    - azure_keyvault_keyvault
    - azure_network_bastion_hosts
    - azure_security_contacts
    - azure_sql_server_admins
    - azure_network_virtual_networks
    - azure_sql_transparent_data_encryptions
    - azure_applicationinsights_components
    - azure_sql_servers
    - azure_postgresql_servers
    - azure_storage_containers
    - azure_sql_server_databases
    - azure_network_watcher_flow_logs
    - azure_storage_accounts
    - azure_monitor_subscription_diagnostic_settings
    - azure_appservice_web_app_auth_settings
    - azure_keyvault_keyvault_keys
    - azure_sql_server_firewall_rules
    - azure_keyvault_keyvault_secrets
    - azure_monitor_diagnostic_settings
    - azure_storage_blob_services
    - azure_monitor_resources
    - azure_compute_disks
    - azure_mysqlflexibleservers_servers
    - azure_sql_server_blob_auditing_policies
    - azure_network_watchers
    - azure_appservice_web_apps
    - azure_sql_server_database_blob_auditing_policies
    - azure_cosmos_database_accounts
    - azure_mysql_server_configurations
    - azure_monitor_activity_log_alerts
    - azure_mysql_servers
    - azure_appservice_web_app_configurations
    - azure_postgresql_server_firewall_rules
    - azure_subscription_subscriptions
    - azure_policy_assignments
    - azure_network_security_groups
  hipaa_hitrust_v9_2:
    - azure_monitor_activity_log_alerts
    - azure_security_assessments
    - azure_subscription_subscription_locations
    - azure_search_services
    - azure_keyvault_keyvault
    - azure_network_interfaces
    - azure_storage_accounts
    - azure_appservice_web_apps
    - azure_containerservice_managed_clusters
    - azure_monitor_log_profiles
    - azure_sql_servers
    - azure_sql_managed_instance_vulnerability_assessments
    - azure_network_watchers
    - azure_network_security_groups
    - azure_compute_virtual_machine_extensions
    - azure_cosmos_database_accounts
    - azure_containerregistry_registries
    - azure_authorization_role_definitions
    - azure_sql_managed_instance_encryption_protectors
    - azure_authorization_role_assignments
    - azure_mariadb_servers
    - azure_subscription_subscriptions
    - azure_compute_virtual_machines
    - azure_keyvault_keyvault_managed_hsms
    - azure_compute_virtual_machine_scale_sets
    - azure_sql_transparent_data_encryptions
    - azure_sql_server_database_vulnerability_assessment_scans
    - azure_logic_workflows
    - azure_network_virtual_networks
    - azure_sql_server_database_long_term_retention_policies
    - azure_datalakestore_accounts
    - azure_eventhub_namespaces
    - azure_resources_links
    - azure_security_auto_provisioning_settings
    - azure_monitor_diagnostic_settings
    - azure_sql_server_databases
    - azure_sql_server_vulnerability_assessments
    - azure_mysql_servers
    - azure_postgresql_servers
    - azure_redis_caches
    - azure_sql_managed_instances
    - azure_sql_server_blob_auditing_policies
    - azure_sql_server_encryption_protectors
    - azure_streamanalytics_streaming_jobs
    - azure_eventhub_namespace_network_rule_sets
    - azure_appservice_web_app_vnet_connections
    - azure_sql_server_virtual_network_rules
    - azure_batch_account
    - azure_security_jit_network_access_policies
  azure_models:
    - azure_monitor_activity_log_alerts
    - azure_security_assessments
    - azure_subscription_subscription_locations
    - azure_logic_workflows
    - azure_postgresql_servers
    - azure_network_virtual_networks
    - azure_storage_containers
    - azure_sql_server_firewall_rules
    - azure_keyvault_keyvault_keys
    - azure_cosmos_database_accounts
    - azure_applicationinsights_components
    - azure_search_services
    - azure_mysqlflexibleservers_servers
    - azure_containerregistry_registries
    - azure_keyvault_keyvault
    - azure_sql_server_database_long_term_retention_policies
    - azure_datalakestore_accounts
    - azure_redis_caches
    - azure_authorization_role_definitions
    - azure_sql_managed_instance_encryption_protectors
    - azure_eventhub_namespaces
    - azure_sql_managed_instances
    - azure_sql_server_blob_auditing_policies
    - azure_sql_server_encryption_protectors
    - azure_resources_links
    - azure_sql_server_advanced_threat_protection_settings
    - azure_security_auto_provisioning_settings
    - azure_network_interfaces
    - azure_authorization_role_assignments
    - azure_appservice_web_app_auth_settings
    - azure_sql_server_databases
    - azure_keyvault_keyvault_secrets
    - azure_monitor_diagnostic_settings
    - azure_mariadb_servers
    - azure_storage_accounts
    - azure_sql_server_database_blob_auditing_policies
    - azure_subscription_subscriptions
    - azure_security_contacts
    - azure_compute_virtual_machines
    - azure_sql_server_admins
    - azure_monitor_subscription_diagnostic_settings
    - azure_keyvault_keyvault_managed_hsms
    - azure_streamanalytics_streaming_jobs
    - azure_monitor_resources
    - azure_appservice_web_apps
    - azure_containerservice_managed_clusters
    - azure_sql_server_vulnerability_assessments
    - azure_monitor_log_profiles
    - azure_security_pricings
    - azure_storage_blob_services
    - azure_compute_disks
    - azure_network_watcher_flow_logs
    - azure_compute_virtual_machine_scale_sets
    - azure_postgresql_server_configurations
    - azure_sql_servers
    - azure_postgresql_server_firewall_rules
    - azure_mysql_servers
    - azure_mysqlflexibleservers_server_configurations
    - azure_sql_managed_instance_vulnerability_assessments
    - azure_sql_transparent_data_encryptions
    - azure_network_watchers
    - azure_network_security_groups
    - azure_eventhub_namespace_network_rule_sets
    - azure_network_bastion_hosts
    - azure_appservice_web_app_vnet_connections
    - azure_mysql_server_configurations
    - azure_sql_server_virtual_network_rules
    - azure_compute_virtual_machine_extensions
    - azure_batch_account
    - azure_sql_server_database_vulnerability_assessment_scans
    - azure_security_jit_network_access_policies
    - azure_appservice_web_app_configurations
    - azure_policy_assignments
