with
    aggregated as (
    ({{ security_account_information_provided('cis_v3.0.0','1.2') }})
        {{ union() }}
    ({{ iam_root_user_no_access_keys('cis_v3.0.0','1.4') }})
        {{ union() }}
    ({{ mfa_enabled_for_root('cis_v3.0.0','1.5') }})
        {{ union() }}
    ({{ hardware_mfa_enabled_for_root('cis_v3.0.0','1.6') }})
        {{ union() }}
    ({{ iam_root_last_used('cis_v3.0.0','1.7') }})
        {{ union() }}
    ({{ password_policy_min_length('cis_v3.0.0','1.8') }})
        {{ union() }}
    ({{ password_policy_prevent_reuse('cis_v3.0.0','1.9') }})
        {{ union() }}
    ({{ mfa_enabled_for_console_access('cis_v3.0.0','1.10') }})
        {{ union() }}
    ({{ iam_user_access_keys_and_password_at_setup('cis_v3.0.0','1.11') }})
        {{ union() }}
    ({{ unused_creds_disabled_45_days('cis_v3.0.0','1.12') }})
        {{ union() }}
    ({{ users_with_two_active_access_keys('cis_v3.0.0','1.13') }})
        {{ union() }}
    ({{ old_access_keys('cis_v3.0.0','1.14') }})
        {{ union() }}
    ({{ policies_attached_to_groups_roles('cis_v3.0.0','1.15') }})
        {{ union() }}
    ({{ no_star('cis_v3.0.0','1.16') }})
        {{ union() }}
    ({{ iam_support_role('cis_v3.0.0','1.17') }})
        {{ union() }}
    ({{ use_iam_roles_for_instances('cis_v3.0.0','1.18') }})
        {{ union() }}
    ({{ iam_server_certificate_not_expired('cis_v3.0.0','1.19') }})
        {{ union() }}
    ({{ regions_with_no_accessanalyzers('cis_v3.0.0','1.20') }})
        {{ union() }}
    ({{ iam_users_are_managed_centrally('cis_v3.0.0','1.21') }})
        {{ union() }}
    ({{ iam_user_group_role_cloudshell_fullaccess_restricted('cis_v3.0.0','1.22') }})
        {{ union() }}
    ({{ deny_http_requests('cis_v3.0.0','2.1.1') }})
        {{ union() }}
    ({{ mfa_delete('cis_v3.0.0','2.1.2') }})
        {{ union() }}
    ({{ account_level_public_access_blocks('cis_v3.0.0','2.1.4') }})
        {{ union() }}
    ({{ unencrypted_ebs_volumes('cis_v3.0.0','2.2.1') }})
        {{ union() }}
    ({{ instances_should_have_ecnryption_at_rest_enabled('cis_v3.0.0','2.3.1') }})
        {{ union() }}
    ({{ redis_clusters_have_autominorversionupgrade('cis_v3.0.0','2.3.2') }})
        {{ union() }}
    ({{ rds_db_instances_should_prohibit_public_access('cis_v3.0.0','2.3.3') }})
        {{ union() }}
    ({{ unencrypted_efs_filesystems('cis_v3.0.0','2.4.1') }})
        {{ union() }}
    ({{ cloudtrail_enabled_all_regions('cis_v3.0.0','3.1') }})
        {{ union() }}
    ({{ log_file_validation_enabled('cis_v3.0.0','3.2') }})
        {{ union() }}
    ({{ config_enabled_all_regions('cis_v3.0.0','3.3') }})
        {{ union() }}
    ({{ bucket_access_logging('cis_v3.0.0','3.4') }})
        {{ union() }}
    ({{ logs_encrypted('cis_v3.0.0','3.5') }})
        {{ union() }}
    ({{ rotation_enabled_for_customer_key('cis_v3.0.0','3.6') }})
        {{ union() }}
    ({{ flow_logs_enabled_in_all_vpcs('cis_v3.0.0','3.7') }})
        {{ union() }}
    ({{ cloudtrail_s3_object_write_events_audit_enabled('cis_v3.0.0','3.8') }})
        {{ union() }}
    ({{ cloudtrail_s3_object_read_events_audit_enabled('cis_v3.0.0','3.9') }})
        {{ union() }}
    ({{ alarm_unauthorized_api('cis_v3.0.0','4.1') }})
        {{ union() }}
    ({{ alarm_console_no_mfa('cis_v3.0.0','4.2') }})
        {{ union() }}
    ({{ alarm_root_account('cis_v3.0.0','4.3') }})
        {{ union() }}
    ({{ alarm_iam_policy_change('cis_v3.0.0','4.4') }})
        {{ union() }}
    ({{ alarm_cloudtrail_config_changes('cis_v3.0.0','4.5') }})
        {{ union() }}
    ({{ alarm_console_auth_failure('cis_v3.0.0','4.6') }})
        {{ union() }}
    ({{ alarm_delete_customer_cmk('cis_v3.0.0','4.7') }})
        {{ union() }}
    ({{ alarm_s3_bucket_policy_change('cis_v3.0.0','4.8') }})
        {{ union() }}
    ({{ alarm_aws_config_changes('cis_v3.0.0','4.9') }})
        {{ union() }}
    ({{ alarm_security_group_changes('cis_v3.0.0','4.10') }})
        {{ union() }}
    ({{ alarm_nacl_changes('cis_v3.0.0','4.11') }})
        {{ union() }}
    ({{ alarm_network_gateways('cis_v3.0.0','4.12') }})
        {{ union() }}
    ({{ alarm_route_table_changes('cis_v3.0.0','4.13') }})
        {{ union() }}
    ({{ alarm_vpc_changes('cis_v3.0.0','4.14') }})
        {{ union() }}
    ({{ alarm_organization_changes('cis_v3.0.0','4.15') }})
        {{ union() }}
    ({{ securityhub_enabled('cis_v3.0.0','4.16') }})
        {{ union() }}
    ({{ vpc_network_acl_remote_administration('cis_v3.0.0','5.1') }})
        {{ union() }}
    ({{ vpc_security_group_remote_administration_ipv4('cis_v3.0.0','5.2') }})
        {{ union() }}
    ({{ no_broad_public_ipv6_ingress_on_port_22_3389('cis_v3.0.0','5.3') }})
        {{ union() }}
    ({{ default_sg_no_access('cis_v3.0.0','5.4') }})
        {{ union() }}
    ({{ ec2_not_imdsv2_instances('cis_v3.0.0','5.6') }})
    )
select 
        {{ gen_timestamp() }},
        aggregated.*
from aggregated
