name: gcp_compliance
version: 0.4.0
config-version: 2
profile: gcp_compliance
model-paths:
  - models
  - ../models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
  - ../macros
  - ../../macros
snapshot-paths:
  - snapshots
clean-targets:
  - target
  - dbt_packages
models:
  gcp_compliance: null





#vars
vars:
  cis_v1_2_0:
    - gcp_dns_policies
    - gcp_sql_instances
    - gcp_resourcemanager_project_policies
    - gcp_iam_service_accounts
    - gcp_firewall_allowed_rules
    - gcp_iam_service_account_keys
    - gcp_compute_disks
    - gcp_bigquery_datasets
    - gcp_compute_subnetworks
    - gcp_compute_ssl_policies
    - gcp_storage_bucket_policies
    - gcp_kms_crypto_keys
    - gcp_bigquery_tables
    - gcp_public_buckets_accesses
    - gcp_compute_firewalls
    - gcp_compute_networks
    - gcp_storage_buckets
    - gcp_compute_instances
    - gcp_logging_metrics
    - gcp_logging_sinks
    - gcp_compute_projects
    - gcp_compute_target_ssl_proxies
    - gcp_dns_managed_zones

  cis_v2_0_0:
    - gcp_dns_policies
    - gcp_accessapproval_project_settings
    - gcp_sql_instances
    - gcp_resourcemanager_project_policies
    - gcp_iam_service_accounts
    - gcp_firewall_allowed_rules
    - gcp_iam_service_account_keys
    - gcp_compute_disks
    - gcp_bigquery_datasets
    - gcp_compute_subnetworks
    - gcp_accessapproval_folder_settings
    - gcp_compute_ssl_policies
    - gcp_compute_url_maps
    - gcp_storage_bucket_policies
    - gcp_apikeys_keys
    - gcp_kms_crypto_keys
    - gcp_bigquery_tables
    - gcp_serviceusage_services
    - gcp_compute_backend_services
    - gcp_public_buckets_accesses
    - gcp_essentialcontacts_project_contacts
    - gcp_compute_firewalls
    - gcp_compute_networks
    - gcp_storage_buckets
    - gcp_compute_instances
    - gcp_dataproc_clusters
    - gcp_logging_metrics
    - gcp_essentialcontacts_folder_contacts
    - gcp_logging_sinks
    - gcp_compute_projects
    - gcp_accessapproval_organization_settings
    - gcp_compute_target_ssl_proxies
    - gcp_dns_managed_zones
    - gcp_essentialcontacts_organization_contacts

  gcp_models:
    - gcp_dns_policies
    - gcp_accessapproval_project_settings
    - gcp_sql_instances
    - gcp_storage_buckets
    - gcp_compute_backend_services
    - gcp_iam_service_account_keys
    - gcp_compute_disks
    - gcp_compute_instances
    - gcp_dataproc_clusters
    - gcp_logging_metrics
    - gcp_bigquery_datasets
    - gcp_compute_subnetworks
    - gcp_essentialcontacts_folder_contacts
    - gcp_resourcemanager_project_policies
    - gcp_public_buckets_accesses
    - gcp_iam_service_accounts
    - gcp_firewall_allowed_rules
    - gcp_logging_sinks
    - gcp_compute_projects
    - gcp_accessapproval_folder_settings
    - gcp_essentialcontacts_project_contacts
    - gcp_compute_ssl_policies
    - gcp_compute_target_ssl_proxies
    - gcp_compute_url_maps
    - gcp_accessapproval_organization_settings
    - gcp_compute_firewalls
    - gcp_dns_managed_zones
    - gcp_storage_bucket_policies
    - gcp_apikeys_keys
    - gcp_kms_crypto_keys
    - gcp_bigquery_tables
    - gcp_compute_networks
    - gcp_essentialcontacts_organization_contacts
    - gcp_serviceusage_services
