name: gcp_asset_inventory
version: 1.3.8
config-version: 2
profile: gcp_asset_inventory
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
  - ../../macros
snapshot-paths:
  - snapshots
clean-targets:
  - target
  - dbt_packages
models: null
