name: aws_compliance
version: 1.12.2
config-version: 2
profile: aws_compliance
model-paths:
  - models
  - ../models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - ../macros
  - ../../macros
snapshot-paths:
  - snapshots
clean-targets:
  - target
  - dbt_packages
dispatch:
  - macro_namespace: dbt_utils
    search_order:
      - aws_compliance
      - dbt_utils
vars:
  cis_v1_2_0:
    - aws_iam_password_policies
    - aws_iam_users
    - aws_iam_credential_reports
    - aws_s3_bucket_loggings
    - aws_iam_user_attached_policies
    - aws_iam_user_access_keys
    - aws_s3_buckets
    - aws_cloudtrail_trail_event_selectors
    - aws_ec2_vpcs
    - aws_iam_user_policies
    - aws_cloudtrail_trails
    - aws_kms_keys
    - aws_ec2_flow_logs
    - aws_iam_virtual_mfa_devices
    - aws_ec2_security_groups
    - aws_sns_subscriptions
    - aws_cloudwatchlogs_metric_filters
    - aws_cloudwatch_alarms
  cis_v2_0_0:
    - aws_iam_password_policies
    - aws_iam_user_attached_policies
    - aws_iam_instance_profiles
    - aws_efs_filesystems
    - aws_ec2_vpcs
    - aws_iam_roles
    - aws_s3_bucket_grants
    - aws_accessanalyzer_analyzers
    - aws_cloudtrail_trails
    - aws_iam_server_certificates
    - aws_ec2_flow_logs
    - aws_s3_bucket_versionings
    - aws_iam_user_access_keys
    - aws_iam_role_attached_policies
    - aws_iam_accounts
    - aws_iam_credential_reports
    - aws_iam_users
    - aws_securityhub_hubs
    - aws_cloudtrail_trail_event_selectors
    - aws_iam_policy_versions
    - aws_s3_bucket_policies
    - aws_rds_instances
    - aws_ec2_ebs_volumes
    - aws_config_configuration_recorders
    - aws_iam_saml_identity_providers
    - aws_kms_keys
    - aws_ec2_instances
    - aws_iam_group_attached_policies
    - aws_s3_buckets
    - aws_iam_virtual_mfa_devices
    - aws_iam_policies
    - aws_regions
    - aws_account_alternate_contacts
    - aws_elasticache_clusters
    - aws_s3_bucket_loggings
    - aws_iam_user_policies
    - aws_s3_accounts
    - aws_ec2_security_groups
    - aws_iam_openid_connect_identity_providers
    - aws_sns_subscriptions
    - aws_ec2_network_acls
    - aws_cloudwatchlogs_metric_filters
    - aws_cloudwatch_alarms
  cis_v3_0_0:
    - aws_iam_password_policies
    - aws_iam_user_attached_policies
    - aws_iam_instance_profiles
    - aws_efs_filesystems
    - aws_ec2_vpcs
    - aws_iam_roles
    - aws_accessanalyzer_analyzers
    - aws_cloudtrail_trails
    - aws_iam_server_certificates
    - aws_ec2_flow_logs
    - aws_s3_bucket_versionings
    - aws_iam_user_access_keys
    - aws_iam_role_attached_policies
    - aws_iam_accounts
    - aws_iam_credential_reports
    - aws_iam_users
    - aws_securityhub_hubs
    - aws_cloudtrail_trail_event_selectors
    - aws_iam_policy_versions
    - aws_s3_bucket_policies
    - aws_rds_instances
    - aws_ec2_ebs_volumes
    - aws_config_configuration_recorders
    - aws_iam_saml_identity_providers
    - aws_kms_keys
    - aws_ec2_instances
    - aws_iam_group_attached_policies
    - aws_s3_buckets
    - aws_iam_virtual_mfa_devices
    - aws_iam_policies
    - aws_regions
    - aws_account_alternate_contacts
    - aws_elasticache_clusters
    - aws_s3_bucket_loggings
    - aws_iam_user_policies
    - aws_s3_accounts
    - aws_ec2_security_groups
    - aws_iam_openid_connect_identity_providers
    - aws_cloudwatchlogs_metric_filters
    - aws_sns_subscriptions
    - aws_ec2_network_acls
    - aws_cloudwatch_alarms
  foundational_security:
    - aws_iam_password_policies
    - aws_rds_clusters
    - aws_elbv2_load_balancers
    - aws_rds_db_snapshots
    - aws_redshift_cluster_parameters
    - aws_s3_bucket_grants
    - aws_apigatewayv2_api_routes
    - aws_cloudtrail_trails
    - aws_ssm_instance_compliance_items
    - aws_ec2_flow_logs
    - aws_s3_bucket_versionings
    - aws_waf_rules
    - aws_iam_user_access_keys
    - aws_rds_cluster_snapshots
    - aws_ecs_cluster_services
    - aws_iam_role_policies
    - aws_ec2_ebs_volumes
    - aws_networkfirewall_firewall_policies
    - aws_autoscaling_launch_configurations
    - aws_sns_topics
    - aws_acm_certificates
    - aws_secretsmanager_secrets
    - aws_ec2_ebs_snapshot_attributes
    - aws_iam_virtual_mfa_devices
    - aws_elasticache_clusters
    - aws_neptune_cluster_snapshots
    - aws_dms_replication_instances
    - aws_iam_group_policies
    - aws_s3_accounts
    - aws_applicationautoscaling_policies
    - aws_ssm_instances
    - aws_wafregional_rule_groups
    - aws_ssm_documents
    - aws_redshift_cluster_parameter_groups
    - aws_iam_accounts
    - aws_iam_credential_reports
    - aws_sagemaker_notebook_instances
    - aws_eks_clusters
    - aws_elasticbeanstalk_environments
    - aws_redshift_clusters
    - aws_stepfunctions_state_machines
    - aws_kms_keys
    - aws_kms_key_rotation_statuses
    - aws_lambda_functions
    - aws_ec2_instances
    - aws_ec2_regional_configs
    - aws_ec2_launch_template_versions
    - aws_docdb_clusters
    - aws_ec2_network_acls
    - aws_iam_groups
    - aws_elasticbeanstalk_configuration_settings
    - aws_s3_bucket_loggings
    - aws_account_alternate_contacts
    - aws_sqs_queues
    - aws_wafregional_rules
    - aws_rds_events
    - aws_ecr_repository_lifecycle_policies
    - aws_dax_clusters
    - aws_ec2_security_groups
    - aws_efs_filesystems
    - aws_apigatewayv2_api_stages
    - aws_iam_roles
    - aws_dynamodb_table_continuous_backups
    - aws_codebuild_projects
    - aws_ec2_network_interfaces
    - aws_waf_rule_groups
    - aws_elbv2_listeners
    - aws_iam_policy_versions
    - aws_apigatewayv2_apis
    - aws_ecs_task_definitions
    - aws_ec2_subnets
    - aws_ecr_repositories
    - aws_ec2_transit_gateways
    - aws_s3_buckets
    - aws_wafv2_web_acls
    - aws_kinesis_streams
    - aws_iam_policies
    - aws_regions
    - aws_lambda_runtimes
    - aws_elbv2_load_balancer_attributes
    - aws_cloudformation_stacks
    - aws_iam_user_policies
    - aws_emr_clusters
    - aws_ec2_vpn_connections
    - aws_s3_bucket_lifecycles
    - aws_s3_bucket_notification_configurations
    - aws_ec2_vpc_endpoints
    - aws_iam_user_attached_policies
    - aws_apigateway_rest_api_stages
    - aws_s3_bucket_encryption_rules
    - aws_dynamodb_tables
    - aws_ec2_vpcs
    - aws_athena_work_groups
    - aws_waf_web_acls
    - aws_guardduty_detectors
    - aws_elasticache_replication_groups
    - aws_iam_users
    - aws_appsync_graphql_apis
    - aws_autoscaling_groups
    - aws_neptune_clusters
    - aws_cloudtrail_trail_event_selectors
    - aws_s3_bucket_object_lock_configurations
    - aws_efs_access_points
    - aws_s3_bucket_policies
    - aws_rds_instances
    - aws_config_configuration_recorders
    - aws_cloudfront_distributions
    - aws_elbv1_load_balancer_policies
    - aws_wafregional_web_acls
    - aws_apigateway_rest_apis
    - aws_ecs_clusters
    - aws_s3_bucket_public_access_blocks
    - aws_elbv1_load_balancers
    - aws_elasticsearch_domains
    - aws_networkfirewall_rule_groups
  pci_dss_v3_2_1:
    - aws_iam_password_policies
    - aws_iam_user_attached_policies
    - aws_s3_bucket_replications
    - aws_s3_bucket_encryption_rules
    - aws_ssm_instances
    - aws_ec2_vpcs
    - aws_s3_bucket_grants
    - aws_cloudtrail_trails
    - aws_waf_web_acls
    - aws_ssm_instance_compliance_items
    - aws_ec2_flow_logs
    - aws_guardduty_detectors
    - aws_ec2_eips
    - aws_iam_user_access_keys
    - aws_iam_users
    - aws_iam_credential_reports
    - aws_rds_cluster_snapshots
    - aws_iam_accounts
    - aws_codebuild_projects
    - aws_autoscaling_groups
    - aws_sagemaker_notebook_instances
    - aws_cloudtrail_trail_event_selectors
    - aws_elbv2_listeners
    - aws_iam_policy_versions
    - aws_redshift_clusters
    - aws_s3_bucket_policies
    - aws_rds_instances
    - aws_config_configuration_recorders
    - aws_kms_keys
    - aws_lambda_functions
    - aws_ec2_instances
    - aws_s3_buckets
    - aws_wafv2_web_acls
    - aws_secretsmanager_secrets
    - aws_ec2_ebs_snapshot_attributes
    - aws_iam_virtual_mfa_devices
    - aws_iam_policies
    - aws_regions
    - aws_s3_bucket_public_access_blocks
    - aws_elasticsearch_domains
    - aws_dms_replication_instances
    - aws_iam_user_policies
    - aws_s3_accounts
    - aws_ec2_security_groups
    - aws_sns_subscriptions
    - aws_cloudwatch_alarms
    - aws_cloudwatchlogs_metric_filters
  imds_v2:
    - aws_ec2_images
    - aws_ec2_instances
    - aws_lightsail_instances
  public_egress:
    - aws_ec2_instances
    - aws_ec2_security_groups
    - aws_ec2_route_tables
    - aws_lambda_functions
  publicly_available:
    - aws_cloudfront_distributions
    - aws_ec2_instances
    - aws_elbv1_load_balancers
    - aws_apigateway_rest_apis
    - aws_elbv2_load_balancers
    - aws_redshift_clusters
    - aws_apigatewayv2_apis
    - aws_rds_instances
  aws_models:
    - aws_s3_bucket_notification_configurations
    - aws_iam_password_policies
    - aws_ec2_vpc_endpoints
    - aws_iam_user_attached_policies
    - aws_applicationautoscaling_policies
    - aws_iam_instance_profiles
    - aws_s3_bucket_replications
    - aws_ec2_route_tables
    - aws_apigateway_rest_api_stages
    - aws_s3_bucket_encryption_rules
    - aws_efs_filesystems
    - aws_ssm_instances
    - aws_rds_clusters
    - aws_apigatewayv2_api_stages
    - aws_dynamodb_tables
    - aws_ec2_vpcs
    - aws_elbv2_load_balancers
    - aws_iam_roles
    - aws_wafregional_rule_groups
    - aws_dynamodb_table_continuous_backups
    - aws_rds_db_snapshots
    - aws_redshift_cluster_parameters
    - aws_s3_bucket_grants
    - aws_ssm_documents
    - aws_accessanalyzer_analyzers
    - aws_athena_work_groups
    - aws_apigatewayv2_api_routes
    - aws_cloudtrail_trails
    - aws_iam_server_certificates
    - aws_ssm_instance_compliance_items
    - aws_waf_web_acls
    - aws_redshift_cluster_parameter_groups
    - aws_ec2_flow_logs
    - aws_guardduty_detectors
    - aws_ec2_eips
    - aws_s3_bucket_versionings
    - aws_waf_rules
    - aws_iam_user_access_keys
    - aws_iam_role_attached_policies
    - aws_elasticache_replication_groups
    - aws_iam_credential_reports
    - aws_iam_users
    - aws_iam_accounts
    - aws_rds_cluster_snapshots
    - aws_appsync_graphql_apis
    - aws_lightsail_instances
    - aws_ecs_cluster_services
    - aws_codebuild_projects
    - aws_ec2_network_interfaces
    - aws_autoscaling_groups
    - aws_securityhub_hubs
    - aws_sagemaker_notebook_instances
    - aws_neptune_clusters
    - aws_waf_rule_groups
    - aws_iam_role_policies
    - aws_eks_clusters
    - aws_elasticbeanstalk_environments
    - aws_cloudtrail_trail_event_selectors
    - aws_s3_bucket_object_lock_configurations
    - aws_elbv2_listeners
    - aws_efs_access_points
    - aws_iam_policy_versions
    - aws_s3_bucket_policies
    - aws_redshift_clusters
    - aws_rds_instances
    - aws_apigatewayv2_apis
    - aws_ec2_ebs_volumes
    - aws_config_configuration_recorders
    - aws_stepfunctions_state_machines
    - aws_ecs_task_definitions
    - aws_networkfirewall_firewall_policies
    - aws_ec2_subnets
    - aws_iam_saml_identity_providers
    - aws_kms_keys
    - aws_lambda_functions
    - aws_autoscaling_launch_configurations
    - aws_sns_topics
    - aws_cloudfront_distributions
    - aws_elbv1_load_balancer_policies
    - aws_wafregional_web_acls
    - aws_acm_certificates
    - aws_ec2_instances
    - aws_iam_group_attached_policies
    - aws_ec2_regional_configs
    - aws_ec2_launch_template_versions
    - aws_docdb_clusters
    - aws_ecr_repositories
    - aws_ec2_transit_gateways
    - aws_apigateway_rest_apis
    - aws_s3_buckets
    - aws_wafv2_web_acls
    - aws_secretsmanager_secrets
    - aws_ec2_network_acls
    - aws_ec2_ebs_snapshot_attributes
    - aws_iam_groups
    - aws_ecs_clusters
    - aws_elasticbeanstalk_configuration_settings
    - aws_iam_virtual_mfa_devices
    - aws_kinesis_streams
    - aws_iam_policies
    - aws_regions
    - aws_lambda_runtimes
    - aws_s3_bucket_public_access_blocks
    - aws_ec2_images
    - aws_s3_bucket_loggings
    - aws_account_alternate_contacts
    - aws_elasticache_clusters
    - aws_elbv2_load_balancer_attributes
    - aws_cloudformation_stacks
    - aws_sqs_queues
    - aws_neptune_cluster_snapshots
    - aws_elbv1_load_balancers
    - aws_wafregional_rules
    - aws_elasticsearch_domains
    - aws_rds_events
    - aws_ecr_repository_lifecycle_policies
    - aws_dms_replication_instances
    - aws_iam_group_policies
    - aws_networkfirewall_rule_groups
    - aws_iam_user_policies
    - aws_dax_clusters
    - aws_emr_clusters
    - aws_s3_accounts
    - aws_ec2_vpn_connections
    - aws_ec2_security_groups
    - aws_iam_openid_connect_identity_providers
    - aws_s3_bucket_lifecycles
    - aws_cloudwatchlogs_metric_filters
    - aws_sns_subscriptions
    - aws_cloudwatch_alarms
