name: aws_data_resilience
version: 2.1.7
config-version: 2
profile: aws_data_resilience
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
  - ../macros
  - ../../macros
snapshot-paths:
  - snapshots
clean-targets:
  - target
  - dbt_packages
models: null
