{
 "title": "Compliance Dashboard - Summary",
 "description": "Gain insights into CIS Kubernetes v1.7.0 compliance status and track policy adherence with this comprehensive dashboard.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "select context from k8s_policy_results\ngroup by context"
   }
  ]
 },
 "panels": [
  {
   "title": "CIS Kubernetes v1.7.0 Compliance Dashboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Success vs. Fail Distribution",
   "type": "piechart",
   "description": "This pie chart provides a visual representation of the distribution between successful and failed cases",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\nWITH complaince as (\nselect \n\t\t'api_server' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%api_server%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'etcd' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%etcd%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'logging' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%logging%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'controller_manager' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%controller_manager%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'scheduler' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%scheduler%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'authentication' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%authentication%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'kubelet' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%kubelet%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'rbac_and_service_accounts' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%rbac_and_service_accounts%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'pod_security' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%pod_security%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'network' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%network%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'secrets' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%secrets%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'general' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%general%'\n\tGROUP BY check_id) as a\n)\nselect sum(failed) as fail,  sum(success) as success\nfrom complaince\n"
    }
   ]
  },
  {
   "title": "Failed Checks",
   "type": "stat",
   "description": "This pie chart provides a visual representation of the distribution between successful and failed cases",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\nWITH complaince as (\nselect \n\t\t'api_server' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%api_server%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'etcd' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%etcd%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'logging' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%logging%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'controller_manager' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%controller_manager%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'scheduler' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%scheduler%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'authentication' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%authentication%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'kubelet' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%kubelet%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'rbac_and_service_accounts' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%rbac_and_service_accounts%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'pod_security' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%pod_security%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'network' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%network%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'secrets' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%secrets%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'general' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%general%'\n\tGROUP BY check_id) as a\n)\nselect sum(failed) as fail\nfrom complaince\n"
    }
   ]
  },
  {
   "title": "Overview by Section",
   "type": "gauge",
   "description": "Visualizes the compliance status of policies categorized by sections such as 'etcd,' 'logging,' and 'api_server.' Failed policies are highlighted to draw immediate attention, helping you quickly identify areas that require corrective action.",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH complaince as (\nselect \n\t\t'Components' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%api_server%' or check_id like '%controller_manager%' or check_id like '%scheduler%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'etcd' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%etcd%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'Configuration' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%authentication%' or check_id like '%logging%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'Policies' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%rbac_and_service_accounts%' \n\t or check_id like '%pod_security%' \n\t or check_id like '%network%' \n\t or check_id like '%secrets%' \n\t or check_id like '%general%'\n\tGROUP BY check_id) as a\n),\ntable1 as (\n\tselect Title, \n       (CAST(success AS DECIMAL) / all_policies) * 100 as percentage\nfrom complaince\n)\nSELECT\n    MAX(CASE WHEN Title = 'Components' THEN percentage END) AS \"Components\",\n    MAX(CASE WHEN Title = 'etcd' THEN percentage END) AS \"etcd\",\n    MAX(CASE WHEN Title = 'Configuration' THEN percentage END) AS \"Configuration\",\n\tMAX(CASE WHEN Title = 'Policies' THEN percentage END) AS \"Policies\"\nFROM table1;\n"
    }
   ]
  },
  {
   "title": "Passed Checks",
   "type": "stat",
   "description": "This pie chart provides a visual representation of the distribution between successful and failed cases",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\nWITH complaince as (\nselect \n\t\t'api_server' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%api_server%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'etcd' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%etcd%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'logging' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%logging%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'controller_manager' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%controller_manager%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'scheduler' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%scheduler%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'authentication' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%authentication%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'kubelet' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%kubelet%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'rbac_and_service_accounts' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%rbac_and_service_accounts%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'pod_security' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%pod_security%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'network' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%network%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'secrets' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%secrets%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'general' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%general%'\n\tGROUP BY check_id) as a\n)\nselect sum(success) as success\nfrom complaince\n"
    }
   ]
  },
  {
   "title": "Components",
   "type": "stat",
   "description": "This pie chart provides a visual representation of the distribution between successful and failed cases",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS \"Successful\",\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS \"Failed\"\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%api_server%' or check_id like '%controller_manager%' or check_id like '%scheduler%'\n\tGROUP BY check_id) as a\n"
    }
   ]
  },
  { "title": "etcd", "gridPos": { "h": 5, "w": 3, "x": 15, "y": 12 } },
  {
   "title": "Configuration",
   "type": "stat",
   "description": "This pie chart provides a visual representation of the distribution between successful and failed cases",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS \"Successful\",\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS \"Failed\"\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%authentication%' or check_id like '%logging%'\n\tGROUP BY check_id) as a\n"
    }
   ]
  },
  {
   "title": "Policies",
   "type": "stat",
   "description": "This pie chart provides a visual representation of the distribution between successful and failed cases",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS \"Successful\",\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS \"Failed\"\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\nwhere check_id like '%rbac_and_service_accounts%' \n\t or check_id like '%pod_security%' \n\t or check_id like '%network%' \n\t or check_id like '%secrets%' \n\t or check_id like '%general%'\n\t GROUP BY check_id) as a\n"
    }
   ]
  },
  {
   "title": "Failed Policies Overview",
   "type": "table",
   "description": "This table provides an overview of policies that have failed, including details about the execution time, resource name, resource ID, check ID, and a brief title describing the policy violation.",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "select resource_id as \"resource id\", resource_name as \"resource name\", status, title as reason from k8s_policy_results\nwhere status = 'fail'"
    }
   ]
  },
  {
   "title": "Successful Policies Overview",
   "type": "table",
   "description": "This table provides an overview of policies that have failed, including details about the execution time, resource name, resource ID, check ID, and a brief title describing the policy violation.",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "select resource_id as \"resource id\", resource_name as \"resource name\", status, title as reason from k8s_policy_results\nwhere status = 'pass'"
    }
   ]
  },
  {
   "title": "Total Resources",
   "type": "stat",
   "description": "This panel displays the count of resources",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct resource_id) as count_resources from k8s_policy_results"
    }
   ]
  },
  {
   "title": "Non-Compliant Resources",
   "type": "stat",
   "description": "This panel displays the count of resources",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct resource_id) as count_resources \nfrom k8s_policy_results\nwhere status = 'fail' "
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT 'Nodes' AS resource_type, COUNT(*) AS resource_count\nFROM k8s_core_nodes\n"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT 'Pods' AS resource_type, COUNT(*) AS resource_count\nFROM k8s_core_pods\n"
    }
   ]
  },
  {
   "title": "Services",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT 'Services' AS resource_type, COUNT(*) AS resource_count\n    FROM k8s_core_services\n"
    }
   ]
  },
  {
   "title": "ConfigMaps",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "    SELECT 'ConfigMaps' AS resource_type, COUNT(*) AS resource_count\n    FROM k8s_core_config_maps\n"
    }
   ]
  }
 ]
}