.PHONY: build
build:
	rm -rf ./build/aws_asset_inventory
	mkdir -p ./build/aws_asset_inventory
	cp -r grafana README.md ./build/aws_asset_inventory
	zip -r ./build/aws_asset_inventory.zip ./build/aws_asset_inventory
