{
 "title": "Compliance Dashboard - In-Depth Analysis",
 "description": "Gain insights into CIS Kubernetes v1.7.0 compliance status and track policy adherence with this comprehensive dashboard.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "select context from k8s_policy_results\ngroup by context"
   }
  ]
 },
 "panels": [
  {
   "title": "Control Plane Components",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH complaince as (\nselect \n\t\t'API Server' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%api_server%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'Controller Manager' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%controller_manager%'\n\tGROUP BY check_id) as a\nUNION\n\tselect \n\t\t'Scheduler' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%scheduler%'\n\tGROUP BY check_id) as a\n),\ntable1 as (\n\tselect Title, \n       (CAST(success AS DECIMAL) / all_policies) * 100 as percentage\nfrom complaince\n)\nSELECT\n    MAX(CASE WHEN Title = 'API Server' THEN percentage END) AS \"API Server\",\n    MAX(CASE WHEN Title = 'Controller Manager' THEN percentage END) AS \"Controller Manager\",\n    MAX(CASE WHEN Title = 'Scheduler' THEN percentage END) AS \"Scheduler\"\nFROM table1;\n"
    }
   ]
  },
  { "title": "RBAC and Service Accounts", "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 } },
  {
   "title": "Pod Security",
   "type": "stat",
   "description": "This pie chart provides a visual representation of the distribution between successful and failed cases",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS \"Successful\",\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS \"Failed\"\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%pod_security%'\n\tGROUP BY check_id) as a\n"
    }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "description": "This pie chart provides a visual representation of the distribution between successful and failed cases",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS \"Successful\",\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS \"Failed\"\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%network%'\n\tGROUP BY check_id) as a\n"
    }
   ]
  },
  { "title": "Policies Overview by Section", "gridPos": { "h": 16, "w": 12, "x": 12, "y": 5 } },
  { "title": "API Server", "gridPos": { "h": 7, "w": 3, "x": 0, "y": 11 } },
  { "title": "Controller Manager", "gridPos": { "h": 7, "w": 4, "x": 3, "y": 11 } },
  { "title": "Scheduler", "gridPos": { "h": 7, "w": 5, "x": 7, "y": 11 } },
  {
   "title": "Control Plane Configuration",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH complaince as (\n\tselect \n\t\t'Logging' as Title,\n\t\tCOUNT(*) as all_policies,\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS failed,\n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS success\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%logging%'\n\tGROUP BY check_id) as a\n),\ntable1 as (\n\tselect Title, \n       (CAST(success AS DECIMAL) / all_policies) * 100 as percentage\nfrom complaince\n)\nSELECT\n    MAX(CASE WHEN Title = 'Logging' THEN percentage END) AS \"Logging\"\nFROM table1;\n"
    }
   ]
  },
  { "title": "Secrets", "gridPos": { "h": 6, "w": 5, "x": 14, "y": 21 } },
  {
   "title": "General",
   "type": "stat",
   "description": "This pie chart provides a visual representation of the distribution between successful and failed cases",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n\t\tSUM(CASE WHEN failed_checks = 0 THEN 1 ELSE 0 END) AS \"Successful\",\n\t\tSUM(CASE WHEN failed_checks > 0 THEN 1 ELSE 0 END) AS \"Failed\"\n\tfrom \n\t(SELECT\n\tcheck_id,\n\t\tCOUNT(*) AS total_checks,\n\t\tSUM(CASE WHEN status = 'fail' THEN 1 ELSE 0 END) AS failed_checks,\n\t\tSUM(CASE WHEN status = 'pass' THEN 1 ELSE 0 END) AS successful_checks\n\tFROM k8s_policy_results\n\twhere check_id like '%general%'\n\tGROUP BY check_id) as a\n"
    }
   ]
  },
  { "title": "Logging", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 26 } }
 ]
}