name: Publish AWS Data Resilience Transformation

on:
  push:
    tags:
      - "transformation-aws-data-resilience-v*.*.*"

jobs:
  publish-transformation-aws-data-resilience:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: transformations/aws_data_resilience
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update Release Notes
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs/promises');
            const { TRANSFORMATION_DIR } = process.env;
            const { data } = await github.rest.repos.getReleaseByTag({
              owner: "cloudquery",
              repo: context.repo.repo,
              tag: context.ref.replace('refs/tags/', ''),
            });
            const releaseNotes = data.body;
            const changelogPath = `transformations/aws_data_resilience/changelog.md`;
            await fs.writeFile(changelogPath, releaseNotes);
      - name: Run build
        run: |
          make build
      - name: Setup CloudQuery
        uses: cloudquery/setup-cloudquery@v3
        with:
          version: v3.29.1
      - name: Publish tranformation
        env:
          CLOUDQUERY_API_KEY: ${{ secrets.CLOUDQUERY_API_KEY }}
        run: |
          tag=${{ github.ref_name }}
          version=${tag#"transformation-aws-data-resilience-"}
          cloudquery addon publish manifest-free.json $version -f
