name: Test Snowflake Policies

on:
  pull_request:
    paths:
      - "aws/foundational_security/snowflake/**"
      - ".github/workflows/snowflake_policies.yml.yml"
  push:
    branches:
      - main
    paths:
      - "aws/foundational_security/snowflake/**"
      - ".github/workflows/snowflake_policies.yml.yml"

jobs:
  test-policies:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./aws/foundational_security/snowflake
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: './aws/foundational_security/snowflake/requirements.txt'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Setup CloudQuery
        uses: cloudquery/setup-cloudquery@v3
        with:
          version: 'v3.10.1'
      - name: Migrate DB
        run: cloudquery migrate tests/spec.yml
        env:
          SNOWFLAKE_CONNECTION_STRING: "${{ secrets.SNOW_USER }}:${{ secrets.SNOW_PASSWORD }}@${{ secrets.SNOW_ACCOUNT }}.${{ secrets.SNOW_REGION }}/${{ secrets.SNOW_DATABASE }}/${{ secrets.SNOW_SCHEMA }}?warehouse=${{ secrets.SNOW_WAREHOUSE }}"
      - name: Run all policies
        run: python main.py run-policy
        env:
          SNOW_USER: ${{ secrets.SNOW_USER }}
          SNOW_PASSWORD: ${{ secrets.SNOW_PASSWORD }}
          SNOW_ACCOUNT: ${{ secrets.SNOW_ACCOUNT }}
          SNOW_WAREHOUSE: ${{ secrets.SNOW_WAREHOUSE }}
          SNOW_DATABASE: ${{ secrets.SNOW_DATABASE }}
          SNOW_SCHEMA: ${{ secrets.SNOW_SCHEMA }}
          SNOW_REGION: ${{ secrets.SNOW_REGION }}