name: "Test AWS Compliance Premium Policies: Postgres"

on:
  pull_request:
    paths:
      - "transformations/aws/compliance-premium/**"
      - ".github/workflows/transformations_aws_compliance_premium_postgres.yml"
      - "transformations/aws/macros/**"
      - "transformations/aws/models/**"
      - "transformations/macros/**"
  push:
    branches:
      - main
    paths:
      - "transformations/aws/compliance-premium/**"
      - ".github/workflows/transformations_aws_compliance_premium_postgres.yml"
      - "transformations/aws/macros/**"
      - "transformations/aws/models/**"
      - "transformations/macros/**"

jobs:
  transformations-aws-compliance-premium:
    name: transformations/aws/compliance-premium
    timeout-minutes: 30
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./transformations/aws/compliance-premium
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: pass
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: "./transformations/aws/compliance-premium/requirements.txt"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Setup CloudQuery
        uses: cloudquery/setup-cloudquery@v3
        with:
          version: v4.0.0
      - name: Migrate DB
        run: cloudquery migrate tests/postgres.yml
        env:
          CQ_DSN: postgresql://postgres:pass@localhost:5432/postgres
      - name: Run Policies
        run: |
          dbt run --target dev-pg --profiles-dir ./tests --exclude aws_compliance__foundational_security