name: "Test AWS Cost Policies: Postgres"

on:
  pull_request:
    paths:
      - "transformations/aws/cost/**"
      - ".github/workflows/transformations_aws_cost_postgres.yml"
      - "transformations/aws/macros/**"
      - "transformations/aws/models/**"
      - "transformations/macros/**"
  push:
    branches:
      - main
    paths:
      - "transformations/aws/cost/**"
      - ".github/workflows/transformations_aws_cost_postgres.yml"
      - "transformations/aws/macros/**"
      - "transformations/aws/models/**"
      - "transformations/macros/**"

jobs:
  transformations-aws-cost:
    name: transformations/aws/cost
    timeout-minutes: 30
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./transformations/aws/cost
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: pass
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: "./transformations/aws/cost/requirements.txt"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Setup CloudQuery
        uses: cloudquery/setup-cloudquery@v3
        with:
          version: v4.3.1
      - name: Migrate DB
        run: cloudquery migrate tests/postgres.yml
        env:
          CQ_DSN: postgresql://postgres:pass@localhost:5432/postgres
      - name: Run Policies
        run: |
          dbt seed --target dev-pg --profiles-dir ./tests
          dbt run --target dev-pg --profiles-dir ./tests --vars 'cost_usage_table: cost_check'
