name: Wait for all required workflows to pass

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  prepare:
    uses: ./.github/workflows/changed_files.yml
  wait_for_required_workflows:
    permissions:
      contents: read
      checks: read
    timeout-minutes: 60
    needs: prepare
    name: wait-for-required-workflows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/github-script@v8
        env:
          FILES: ${{ needs.prepare.outputs.changed_files }}
        with:
          script: |
            const script = require('./scripts/workflows/wait_for_required_workflows.js')
            await script({github, context})
